import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  basic: [{ type: "autogenerated", dirName: "basic" }],
  clang: [{ type: "autogenerated", dirName: "clang" }],
  python: [{ type: "autogenerated", dirName: "python" }],
  linux: [{ type: "autogenerated", dirName: "linux" }],
  cs: [{ type: "autogenerated", dirName: "cs" }],
  games: [{ type: "autogenerated", dirName: "games" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}

export default sidebars
