name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          script: |
            docker compose -f /root/Tutorial/docker-compose.yml down

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: build
      
      - run: "ls -al build"

      - uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          ARGS: "-avzr --delete"
          SOURCE: build
          REMOTE_USER: root
          TARGET: /root/Tutorial/build/

      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          script: |
            docker compose -f /root/Tutorial/docker-compose.yml up -d