name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: build
      
      - run: "ls -al"

      # - uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete
      #     path: build
      #     remote_user: root
      #     remote_path: /root/Tutorial/build
      #     remote_host: ${{ secrets.HOST }}
      #     remote_key: ${{ secrets.KEY }}