name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: BUILD
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: RSYNC
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./build
          remote_path: /root/Tutorial/build
          remote_host: ${{ secrets.HOST }}
          remote_user: root
          remote_key: ${{ secrets.KEY }}